title-size:
  type: string
  default: ""
  description: 
    en: 'Choose the size of the title.'
title-weight: 
  type: string
  default: ""
  description: 
    en: 'Choose the weight of the title.'
title-color:
  type: string
  default: ""
  description: 
    en: 'Used in place of a tertiary color. Use hex colors (eg, #0088cc) or names (eg, azure)'
content:
  type: string
  default: ""
  description: 
    en: 'Add some text'
text-size:
  type: string
  default: ""
  description: 
    en: 'Choose the size of the text under the title.'
