title_size:
  type: string
  default: ""
  description: 
    en: 'Choose the size of the title.'
title_weight: 
  type: string
  default: ""
  description: 
    en: 'Choose the weight of the title.'
title_color:
  type: string
  default: ""
  description: 
    en: 'Used in place of a tertiary color. Use hex colors (eg, #0088cc) or names (eg, azure)'
content:
  type: string
  default: ""
  description: 
    en: 'Add some text'
text_size:
  type: string
  default: ""
  description: 
    en: 'Choose the size of the text under the title.'
text_color:
  type: string
  default: ""
  description: 
    en: 'Choose the color of the text.'     
background_image:
  type: string
  default: "https://i.imgur.com/lHbl12Y.jpg"
  description: 
    en: 'The source url for your background image. Tip: You can upload an image to your main theme and use the url from that, 
         but make sure that you do not use "Uploads" section of this component. Any uploads added to this component will be 
         deleted whenever it is updated.'
image_color_background:
  type: string
  default: ""
  description: 
    en: 'Used in place of a background image. Use hex colors (eg, #0088cc) or names (eg, azure)'
