title_size:
  type: string
  default: ""
  description: 
    en: 'Choose the size of the title.'
title_weight: 
  type: string
  default: ""
  description: 
    en: 'Choose the weight of the title.'
title_color:
  type: string
  default: ""
  description: 
    en: 'Used in place of a tertiary color. Use hex colors (eg, #0088cc) or names (eg, azure)'
content:
  type: string
  default: ""
  description: 
    en: 'Add some text'
text_size:
  type: string
  default: ""
  description: 
    en: 'Choose the size of the text under the title.'
text_color:
  type: string
  default: ""
  description: 
    en: 'Choose the color of the text.'     
image_color_background:
  type: string
  default: ""
  description: 
    en: 'Used if the background image is missing. Use hex colors (eg, #0088cc) or names (eg, azure)'
